from turtle import *
speed(30)
 #Отрисовка окна в маленьком доме
def okno_small():
    pendown()
    begin_fill()
    for i in range(2):
        forward(40)
        left(90)
        forward(20)
        left(90)
    end_fill()
    #Отрисовка дома в 
def small_home():
    pensize(2)
    color("gray")
    penup()
    goto(70, -50)
    pendown()
    left(90)
    begin_fill()
    forward(100)
    right(90)
    forward(150)
    right(90)
    forward(100)
    right(90)
    forward(150)
    end_fill()
    penup()
    right(90)
    forward(20)
    right(90)
    forward(30)
    color("yellow")
    okno_small()
    penup()
    forward(60)
    okno_small()
    penup()
    goto(100, 10)
    okno_small()
    penup()
    forward(60)
    okno_small()
    penup()
    goto(0, 0)
small_home()